name: Deployment Pipeline
on:
  release:
    types:
      - created
  workflow_dispatch:
#   push:
#     branches:
#       - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: AWS CodeDeploy
      uses: sourcetoad/aws-codedeploy-action@v1
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        aws_region: us-east-1
        codedeploy_name: app-challenge
        codedeploy_group: group-app-challenge
        codedeploy_register_only: true
        s3_bucket: s3-app-challenge01
        s3_folder: deploy
        max_polling_iterations: 60
        directory: ./
