name: Deployment Pipeline
on:
  release:
    types:
      - created
  workflow_dispatch:
#   push:
#     branches:
#       - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy do Codigo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Analise do codigo
        uses: ./github-action-script/ 
        id: deploy
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          commit_id: ${{ github.sha }}
          application_name: 'server-challenge' ##nome da aplicação criada no CodeDeployy
